const CONFIG = {
    titleWeb: "Hulaan mo",
    introTitle: 'Daniseee',
    introDesc: `What if gala us, treat ko na :>`,
    btnIntro: 'AYOKO',
    title: 'Anong ayoko, di ako payag (¬_¬")',
    desc: 'One more time (っ˘̩╭╮˘̩)っ ',
    btnYes: 'Sige na nga',
    btnNo: 'Ayoko talaga',
    question: 'So When ka free HAHAHA',
    btnReply: 'Send',
    reply: 'Chat mo ko ako na mag-set HAHAHAHAHA',
    mess: 'SM Cab?',
    messDesc: 'Ikaw na bahala sa time.',
    btnAccept: 'Satchel out!',   
}
